apiVersion: v1
kind: Service
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: python-app
  sessionAffinity: None
  type: LoadBalancer