---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adhoc-job
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adhoc-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: adhoc-job
    namespace: kueue-demo
---
apiVersion: batch/v1
kind: Job
metadata:
  name: adhoc-job
  # generateName: demo-job-
  # labels:
  #   kueue.x-k8s.io/queue-name: local-queue-demo
spec:
  # parallelism: 3
  # completions: 3
  # suspend: true
  template:
    spec:
      containers:
      - name: demo-job
        image: registry.redhat.io/openshift4/ose-cli:latest
        command:
          - /bin/bash
          - -c
          - |
            #!/bin/bash
            set -x

            BASE=https://raw.githubusercontent.com/codekow/demo-kueue/refs/heads/main

            for i in $(seq 1 10); do \
              oc create -f ${BASE}/kueue-demo/kueue-job.yaml; \
            done
        resources:
          requests:
            cpu: 1
            memory: "200Mi"
      restartPolicy: Never
      serviceAccount: adhoc-job
      serviceAccountName: adhoc-job
