apiVersion: batch/v1
kind: Job
metadata:
  generateName: demo-job-
  labels:
    kueue.x-k8s.io/queue-name: local-queue-demo
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
      - name: demo-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["30s"]
        resources:
          requests:
            cpu: 1
            memory: "200Mi"
      restartPolicy: Never