---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: hello-world-
  name: hello-world
  namespace: adhoc-admin
spec:
  template:
    spec:
      containers:
        - name: hello-world
          # image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/bash
            - -c
            - /scripts/job.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: hello-world
            defaultMode: 0755
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccount: hello-world
      serviceAccountName: hello-world
