apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/argo-apps
    repoURL: https://github.com/hemang-rh/openshift-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true