apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/cluster-config
    repoURL: https://github.com/hemang-rh/openshift-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
