apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-kueue
spec:
  destination:
    namespace: demo-kueue
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/demo-kueue
    repoURL: https://github.com/hemang-rh/openshift-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
