apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-rhoai-gpu
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/install-rhoai
    repoURL: https://github.com/hemang-rh/openshift-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - Validate=false
    - ApplyOutOfSyncOnly=true
