apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../components/adhoc-admin

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: demo-cleanup
    namespace: adhoc-admin
    files:
      - crds.txt
      - namespaces.txt
      - uninstall.sh
 
patches:
  - path: patch-job.yaml
    target:
      kind: Job
      name: adhoc-admin-helper
