apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: example
    namespace: adhoc-admin
    files:
      - job.sh

patches:
  - path: patch-job.yaml
    target:
      kind: Job
