apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-python-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: python-app
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/hemang-rh/openshift-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true