apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kueue-batch-user-role
  namespace: kueue-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kueue-batch-user-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin
